import type { NexusModSummary } from '../types/mod';

export const MOCK_MODS: NexusModSummary[] = [
  {
    mod_id: 1001,
    name: 'Aurora Weather Suite',
    summary: 'Complete overhaul of Tamriel weather patterns with SKSE-based stability fixes.',
    description:
      'Author confirmed compatibility with Skyrim SE 1.6.1170. Includes SKSE plugin and Address Library dependency. Updated after latest Creation Club patch with additional rain occlusion fixes.',
    version: '2.4.1',
    author: 'FadedNorth',
    mod_page_url: 'https://www.nexusmods.com/skyrimspecialedition/mods/1001',
    picture_url: 'https://images.nexusmods.com/mods/1704/images/1001/1001-aurora.jpg',
    updated_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 5,
    created_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 120,
  },
  {
    mod_id: 2002,
    name: 'Constellation HUD Revamp',
    summary: 'Streamlined UI for Starfield with new mission tracker and controller-friendly prompts.',
    description:
      'Reports from multiple users confirm mod works on version 1.11.36. Added fix for quest log flicker right after the anniversary update.',
    version: '1.3.0',
    author: 'OrbitLine',
    mod_page_url: 'https://www.nexusmods.com/starfield/mods/2002',
    picture_url: 'https://images.nexusmods.com/mods/4187/images/2002/constellation.jpg',
    updated_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 2,
    created_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 60,
  },
  {
    mod_id: 3003,
    name: 'BG3 Immersive Companions',
    summary: 'Adds companion banter with voiced lines. Some reports of minor animation desync on Patch 6.',
    description:
      'Author mentions Karlach idle animation glitch on Patch 6 but otherwise compatible. Two users reporting crash on camp at Patch 5.',
    version: '0.9.5',
    author: 'LarianFan',
    mod_page_url: 'https://www.nexusmods.com/baldursgate3/mods/3003',
    picture_url: 'https://images.nexusmods.com/mods/6950/images/3003/bg3-companions.jpg',
    updated_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 20,
    created_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 90,
  },
  {
    mod_id: 4004,
    name: 'Starfield Velocity Texture Pack',
    summary: 'Ultra-lightweight texture replacements. Author warns not compatible with 1.11.36 yet.',
    description: 'Textures compiled against 1.10.31 pipeline; use caution on later patches until recompiled.',
    version: '0.8.2',
    author: 'DriveColor',
    mod_page_url: 'https://www.nexusmods.com/starfield/mods/4004',
    picture_url: 'https://images.nexusmods.com/mods/4187/images/4004/velocity.jpg',
    updated_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 45,
    created_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 160,
  },
  {
    mod_id: 5005,
    name: 'Skyrim Script Extender (SKSE64)',
    summary: 'Foundation mod required for the majority of complex Skyrim SE mods.',
    description:
      'Critical runtime component, updated hours after 1.6.1170 shipped. Treated as high probability compatible unless explicitly broken.',
    version: '2.2.7',
    author: 'SKSE Team',
    mod_page_url: 'https://www.nexusmods.com/skyrimspecialedition/mods/5005',
    picture_url: 'https://images.nexusmods.com/mods/1704/images/5005/skse.jpg',
    updated_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 1,
    created_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 200,
  },
  {
    mod_id: 6006,
    name: 'BG3 Tactical Spells',
    summary: 'Adds encounter-scaled spell variants. Users reported incompatibility after Hotfix 19.',
    description: 'Author investigating AI bug on Patch 6; not compatible with new AI scripts yet.',
    version: '1.0.0',
    author: 'Mindflayer',
    mod_page_url: 'https://www.nexusmods.com/baldursgate3/mods/6006',
    picture_url: 'https://images.nexusmods.com/mods/6950/images/6006/spells.jpg',
    updated_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 50,
    created_timestamp: Date.now() / 1000 - 60 * 60 * 24 * 180,
  },
];
